[master] Bugfix for latest Gphl changes
* Do not constract widget if the hwobj is not loaded.

Please consider other way of loading hwobj, because now gphl-workflow is hard coded and loading of hwobj fails:

File "/home/karpics/mxcube/mxcubeMaster/HardwareRepository/HardwareObjects/GphlWorkflow.py", line 17, in <module>
    import f90nml
  File "/usr/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named f90nml